[package]
name = "pet_drawer"
version = "0.3.1"
description = "Desktop pet software launcher"
authors = ["PetDrawer"]
edition = "2021"

[lib]
name = "pet_drawer_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
base64 = "0.22"
aes = "0.8"
cipher = { version = "0.4", features = ["alloc", "block-padding"] }
ecb = { version = "0.1", features = ["alloc"] }
md-5 = "0.10"
qrcode = "0.14"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.32", features = ["bundled"] }
tauri = { version = "2", features = ["macos-private-api", "protocol-asset", "tray-icon"] }
tauri-plugin-dialog = "2"
lofty = "0.24.0"
tungstenite = { version = "0.24", default-features = false, features = ["handshake"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_Storage_FileSystem", "Win32_System_Diagnostics_ToolHelp", "Win32_System_Threading", "Win32_UI_Input_KeyboardAndMouse", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging"] }
